/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SidebarLayoutRouteImport } from './routes/_sidebar-layout'
import { Route as SidebarLayoutIndexRouteImport } from './routes/_sidebar-layout/index'
import { Route as SidebarLayoutTimelineRouteImport } from './routes/_sidebar-layout/timeline'
import { Route as SidebarLayoutSettingsRouteImport } from './routes/_sidebar-layout/settings'
import { Route as SidebarLayoutProjectsRouteImport } from './routes/_sidebar-layout/projects'

const SidebarLayoutRoute = SidebarLayoutRouteImport.update({
  id: '/_sidebar-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarLayoutIndexRoute = SidebarLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarLayoutRoute,
} as any)
const SidebarLayoutTimelineRoute = SidebarLayoutTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => SidebarLayoutRoute,
} as any)
const SidebarLayoutSettingsRoute = SidebarLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SidebarLayoutRoute,
} as any)
const SidebarLayoutProjectsRoute = SidebarLayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SidebarLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SidebarLayoutIndexRoute
  '/projects': typeof SidebarLayoutProjectsRoute
  '/settings': typeof SidebarLayoutSettingsRoute
  '/timeline': typeof SidebarLayoutTimelineRoute
}
export interface FileRoutesByTo {
  '/projects': typeof SidebarLayoutProjectsRoute
  '/settings': typeof SidebarLayoutSettingsRoute
  '/timeline': typeof SidebarLayoutTimelineRoute
  '/': typeof SidebarLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sidebar-layout': typeof SidebarLayoutRouteWithChildren
  '/_sidebar-layout/projects': typeof SidebarLayoutProjectsRoute
  '/_sidebar-layout/settings': typeof SidebarLayoutSettingsRoute
  '/_sidebar-layout/timeline': typeof SidebarLayoutTimelineRoute
  '/_sidebar-layout/': typeof SidebarLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects' | '/settings' | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to: '/projects' | '/settings' | '/timeline' | '/'
  id:
    | '__root__'
    | '/_sidebar-layout'
    | '/_sidebar-layout/projects'
    | '/_sidebar-layout/settings'
    | '/_sidebar-layout/timeline'
    | '/_sidebar-layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidebarLayoutRoute: typeof SidebarLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar-layout': {
      id: '/_sidebar-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar-layout/': {
      id: '/_sidebar-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutIndexRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/timeline': {
      id: '/_sidebar-layout/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof SidebarLayoutTimelineRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/settings': {
      id: '/_sidebar-layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SidebarLayoutSettingsRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/projects': {
      id: '/_sidebar-layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof SidebarLayoutProjectsRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
  }
}

interface SidebarLayoutRouteChildren {
  SidebarLayoutProjectsRoute: typeof SidebarLayoutProjectsRoute
  SidebarLayoutSettingsRoute: typeof SidebarLayoutSettingsRoute
  SidebarLayoutTimelineRoute: typeof SidebarLayoutTimelineRoute
  SidebarLayoutIndexRoute: typeof SidebarLayoutIndexRoute
}

const SidebarLayoutRouteChildren: SidebarLayoutRouteChildren = {
  SidebarLayoutProjectsRoute: SidebarLayoutProjectsRoute,
  SidebarLayoutSettingsRoute: SidebarLayoutSettingsRoute,
  SidebarLayoutTimelineRoute: SidebarLayoutTimelineRoute,
  SidebarLayoutIndexRoute: SidebarLayoutIndexRoute,
}

const SidebarLayoutRouteWithChildren = SidebarLayoutRoute._addFileChildren(
  SidebarLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SidebarLayoutRoute: SidebarLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
