/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SidebarLayoutRouteImport } from './routes/_sidebar-layout'
import { Route as SidebarLayoutIndexRouteImport } from './routes/_sidebar-layout/index'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarLayoutRoute = SidebarLayoutRouteImport.update({
  id: '/_sidebar-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarLayoutIndexRoute = SidebarLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SidebarLayoutIndexRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRoutesByTo {
  '/projects': typeof ProjectsRoute
  '/': typeof SidebarLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sidebar-layout': typeof SidebarLayoutRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/_sidebar-layout/': typeof SidebarLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to: '/projects' | '/'
  id: '__root__' | '/_sidebar-layout' | '/projects' | '/_sidebar-layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidebarLayoutRoute: typeof SidebarLayoutRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar-layout': {
      id: '/_sidebar-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar-layout/': {
      id: '/_sidebar-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutIndexRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
  }
}

interface SidebarLayoutRouteChildren {
  SidebarLayoutIndexRoute: typeof SidebarLayoutIndexRoute
}

const SidebarLayoutRouteChildren: SidebarLayoutRouteChildren = {
  SidebarLayoutIndexRoute: SidebarLayoutIndexRoute,
}

const SidebarLayoutRouteWithChildren = SidebarLayoutRoute._addFileChildren(
  SidebarLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SidebarLayoutRoute: SidebarLayoutRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
